
bedrock:
  model_arn: arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0
  model_id : anthropic.claude-3-5-sonnet-20241022-v2
  temperature: 0.7
  max_tokens: 2048
  provider: aws
  region: us-west-2
  runtime: bedrock-runtime
  endpoint_url: https://bedrock-runtime.us-west-2.amazonaws.com
  top_p: 0.9
  frequency_penalty: 0
  presence_penalty: 0
  aws_access_key_id: YOUR_AWS_ACCESS_KEY_ID
  aws_secret_access_key: YOUR_AWS_SECRET_ACCESS_KEY
  aws_session_token: YOUR_AWS_SESSION_TOKEN